# Test case
---
- hosts: localhost
  tasks:
  - name: Install php+nginx+mysql+redis+phpmyadmin+redisadmin
#    yum: name={{ item }} state=present
    yum: name: ['php', 'nginx', 'mysql', 'phpmyadmin', 'redisadmin'] state=present
#    
    with_items:
        - php
        - nginx
        - mysql
        - phpmyadmin
        - redisadmin
