# Test case
---
- hosts: localhost
  tasks:
  - name: Install php+nginx+mysql+redis+phpmyadmin+redisadmin
#    apt: name: ['php', 'nginx', 'mysql', 'phpmyadmin', 'redisadmin'] state=present
#    

    apt: name={{ item }} state=present
    sudo: yes
    with_items:
        - php
        - nginx
#        - mysql
        - phpmyadmin
        - redisadmin
