# Test case
---
- hosts: localhost
  become: yes

  roles:
    - { role: For_Debian, when: ansible_os_family == "Debian" }
    - { role: For_MacOS, when: ansible_os_family == "Darwin" }


      
