# Test case
---
- hosts: localhost
  tasks:
  
  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto
    
  - name: Print the package facts
    ansible.builtin.debug:
      var: ansible_facts.packages
    
    
  - name: Install php+nginx+mysql+redis+phpmyadmin+redisadmin
    become: yes
#    apt: name: ['php', 'nginx', 'mysql', 'phpmyadmin', 'redisadmin'] state=present
    apt: name={{ item }} state=present
    with_items:
        - php
        - nginx
        - phpmyadmin
#        - redisadmin
#        - mysql


