---
  - name: Install nginx
    apt: 
      name: nginx
      state: "{{ nginx_version }}"
    tags: nginx

  - name: Install phpmyadmin
    apt: 
      name: phpmyadmin
      state: "{{ phpmyadmin_version }}"
    tags: phpmyadmin
 
  - name: Install redisadmin
    apt: 
      name: redis-server
      state: '{{ redis_version }}'
    tags: redis-server

  - name: Install mysql-server
    apt: 
      name: mysql-server
      state: '{{ mysql_version }}'
    tags: mysql-server

  - name: Install php
    apt: 
      name: php
      state: "{{ php_version }}"
    tags: php

  - name: Install extra PHP Packages
    apt:
      state=present
      name={{ item|join('-') }}
    with_nested:
    - "php"
    - "{{php_modules}}"