name: Test Ansible

#on:
#  pull_request:
#    branches:
#    - main

on:
  push:
    branches:
    - main


jobs:
  Try_Ansible:
    runs-on: ubuntu-latest
    
    steps:

    - name: Run Ansible Playbook
      # You may pin to the exact commit or the version.
      # uses: arillso/action.playbook@d5b943e503755e062c15771a7aa639bcaf1e4bd2
      uses: arillso/action.playbook@0.0.4
      with:
        # Name of the inventory file in your workspace.
        inventory: hosts
        # Name of the playbook in your workspace.
        playbook: playbook
        # Only run plays and tasks tagged with these values.
        #tags: # optional
        # Level of verbosity, 0 up to 4.
        verbose: 2
